name: Unit testing

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
        racket: [ '8.0', 'current' ]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: ${{ matrix.racket }}
      - name: "Install generic-flonum as package"
        run: raco pkg install --no-cache --auto --name generic-flonum src/
      - name: "Unit tests"
        run: |
          raco test .
